In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2026-01-13 01:51:51.540627: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-01-13 01:51:51.843346: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-01-13 01:51:51.843423: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-01-13 01:51:51.899150: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-01-13 01:51:52.017371: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-01-13 01:51:52.019250: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [2]:
sentences = ['Transformers process text using attention.',
'Words are converted into numerical vectors.',
'Models learn meaning from large data.',
'Embeddings represent words in vector form.',
'Attention helps models understand context.',
'Neural networks improve predictions over time.'
]

In [17]:
## Define Vocab size
vocab_size = 10000

In [18]:
one_hot_representation = [one_hot(words, vocab_size) for words in sentences]
one_hot_representation

[[6417, 5955, 2758, 4190, 873],
 [8397, 7979, 7354, 3823, 2140, 2597],
 [6376, 7648, 4121, 1500, 2640, 6971],
 [1538, 8748, 8397, 6625, 7344, 9487],
 [873, 2568, 6376, 1550, 3756],
 [1917, 7166, 3551, 4367, 860, 5764]]

In [19]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [20]:
## Pad the sentences to make it to equal length
sent_length = 10
embedded_docs = pad_sequences(one_hot_representation, padding='post', maxlen=sent_length)
embedded_docs

array([[6417, 5955, 2758, 4190,  873,    0,    0,    0,    0,    0],
       [8397, 7979, 7354, 3823, 2140, 2597,    0,    0,    0,    0],
       [6376, 7648, 4121, 1500, 2640, 6971,    0,    0,    0,    0],
       [1538, 8748, 8397, 6625, 7344, 9487,    0,    0,    0,    0],
       [ 873, 2568, 6376, 1550, 3756,    0,    0,    0,    0,    0],
       [1917, 7166, 3551, 4367,  860, 5764,    0,    0,    0,    0]],
      dtype=int32)

In [24]:
embedded_docs[0]

array([6417, 5955, 2758, 4190,  873,    0,    0,    0,    0,    0],
      dtype=int32)

In [21]:
## Feature representation

dim=15
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=dim, input_shape=(sent_length, )))
model.compile('adam', 'mse')

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 10, 15)         │       150,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 150,000 (585.94 KB)

 Trainable params: 150,000 (585.94 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


array([[[ 2.0165373e-02, -2.4836158e-02, -1.2545429e-02,  8.3780177e-03,
          6.9927946e-03,  1.9238982e-02,  3.2524321e-02, -3.8499832e-02,
          2.8145257e-02, -1.6935803e-02,  1.4845740e-02,  3.4253191e-02,
         -1.1895813e-02,  3.5243098e-02, -2.4654754e-03],
        [ 4.6678867e-02,  4.9406480e-02,  1.8599343e-02, -3.4522008e-02,
          2.6593518e-02, -4.1907430e-02, -1.5268493e-02,  6.2991306e-04,
          1.9495711e-03, -2.2188807e-02, -3.2094754e-02, -2.0853413e-02,
         -3.6246665e-03,  1.4073025e-02, -2.2390246e-02],
        [ 3.4953538e-02, -4.4257753e-03,  1.4331650e-02, -4.0401220e-02,
         -3.6594678e-02, -2.5389744e-02,  3.3382844e-02, -6.4577945e-03,
          2.2767697e-02,  1.0527216e-02, -2.8845822e-02,  2.4902653e-02,
          2.4375010e-02,  2.5579762e-02,  4.7579695e-02],
        [-4.8508495e-04, -5.2780621e-03, -4.0558875e-02, -2.3840178e-02,
         -3.2184079e-02, -1.4841210e-02,  2.8541837e-02,  2.2854138e-02,
          2.2164967e-02